
#pragma once
#define RAH_VERSION_MAJOR 1
#define RAH_VERSION_MINOR 4
#define RAH_VERSION_PATCH 0
#define RAH_VERSION_BUILD 3

#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)
#define RAH_VERSION_ANSI STRINGIZE(RAH_VERSION_MAJOR) "." STRINGIZE(RAH_VERSION_MINOR) "." STRINGIZE(RAH_VERSION_PATCH) "." STRINGIZE(RAH_VERSION_BUILD)
#define RAH_VERSION L"1.4.0.3"

